namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md
authors:
  - VTB55
description: Collection for creating and managing text files
license:
  - GPL-3.0-or-later
tags:
  - file
  - filesystem
  - utilities
repository: https://github.com/VTB55/my_own_collection
documentation: https://github.com/VTB55/my_own_collection
homepage: https://github.com/VTB55/my_own_collection
issues: https://github.com/VTB55/my_own_collection/issues
